[package]
name = "hyperliquid-node-trades-listener"
version = "0.1.0"
edition = "2024"

[dependencies]
notify = "6.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
log = "0.4"
dotenv = "0.15"
linemux = "0.3"